name: Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

env:
  build_directory: "Executables/net5/Duplicati.Server/bin/Debug/net5.0"

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.x

    - name: Checkout source
      uses: actions/checkout@v2.3.4

    - name: Restore NuGet dependencies
      run: dotnet restore Duplicati.sln

    - name: Build Duplicati
      run: dotnet build --no-restore Duplicati.sln

    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal Duplicati.sln

  ui_tests:
    name: UI tests
    runs-on: ubuntu-latest

    # Some of these steps duplicate those in the unit_tests job above.  This
    # can be cleaned up using a composite run steps action once it supports
    # what we need (https://github.com/actions/runner/issues/646).
    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.x

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip3 install selenium
        pip3 install --upgrade urllib3

    - name: Checkout source
      uses: actions/checkout@v2.3.4

    - name: Restore NuGet dependencies
      run: dotnet restore Duplicati.sln

    - name: Build Duplicati
      run: dotnet build --no-restore -p:DefineConstants=ENABLE_GTK Duplicati.sln

    - name: Run UI tests
      run: |
        # cp -r Duplicati/Server/webroot "${{ env.build_directory }}"/webroot
        # mono "${{ env.build_directory }}"/Duplicati.Server.exe &
        ./Executables/net5/Duplicati.Server/bin/Debug/net5.0/Duplicati.Server &
        python3 guiTests/guiTest.py
